### ISSUE TITLE
Add catalog entry for EdgeVideoAnalytics.starterKit

### ISSUE THREAD

**Issue by dlaboss** [IBMStreams/samples#66]
https://github.com/IBMStreams/streamsx.edgevideoanalytics.starterkit

This starter kit demonstrates an Apache Edgent/OpenCV based "Smart Camera" IoT device performing face detection and publishing detection events to Watson IoT Platform, and a Streams application performing Face Recognition on faces in face detection events.

Languages
- Java

Categories:
- Beginner / General
- Starter kit
- Edge device
- Image Processing
- Video Analytics

Services:
- Bluemix
- Watson IoT Platform
- Apache Edgent

**Comment by natashadsilva** [comment]
@dlaboss Thank you for your detailed submission. The README.md mentions a post/video. This is also supposed to be part of the catalog entry for the sample. Since it isn't ready yet I have added the sample anyway but I am leaving this issue open so that when the Streams app, article/video are ready the catalog will be updated with relevant links. Please update here when that is done.
